"""alpha_probe.py - the external alpha curve for the E2-A winner.

WHY THIS EXISTS
  E2-A won the public board at 55.80591 with alpha = 3.0, and alpha is the ONLY tuned
  quantity anywhere in this model. Everything else - the 12 features, the rank-3 curve
  basis, the projection, the ridge - is fixed and untuned. So alpha is the entire
  hypothesis space, and we have exactly one external point on it.

  Experiment 2 measured, on one protocol with no confound, that our internal ruler
  ANTI-RANKS arms: internal E2-C 42.73 < E2-B 42.99 < E2-A 43.45 while external ran
  E2-A 55.81 < E2-C 62.52 < E2-B 67.27. Spearman rho = -1.00, n = 3, not significant
  but perfectly ordered. The natural consequence is the question this script makes
  answerable: if the internal curve is flat or mis-shaped, then alpha selection is
  exactly where the internal ruler fails, and the external optimum is somewhere the
  internal CV cannot see.

  Two new external points at alpha = 0.3 and alpha = 30.0 bracket the incumbent by two
  grid steps each. Three points spanning four orders of magnitude of regularisation
  turn a single lucky score into a curve, and a CURVE is decidable where one point is
  not.

  - flat across 0.3 / 3 / 30  -> alpha is not the lever; we are at the data ceiling and
    further tuning is uninformative. That is a real, publishable answer.
  - peaked at one end       -> the internal selection picked the wrong side of the
    optimum, which is a mechanism for the anti-ranking, not just a correlation.

A NOTE ON WHAT THIS IS NOT
  This is NOT a resubmission designed to measure board noise. The metric is
  deterministic - fixed labels, fixed public/private split, np.trapezoid EMD - so
  resubmitting an identical file returns an identical score. Resubmission measures
  nothing. This measures the SHAPE of the regularisation response, which is a property
  of the model and is genuinely unknown.

SELECTION DISCIPLINE, restated because it is the rule this whole project keeps breaking
  Two alphas are generated here, in advance, both before any score is seen, and BOTH
  will be submitted. No third alpha. No picking the winner of the three and calling it
  an improvement - the project's own measurement is that selecting the best of N on
  noise buys a large apparent gain, which is exactly how 39.26 became 83.94. These two
  files exist to MAP a curve. The curve is the result; the argmin is incidental.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
for _p in (ROOT / "Model 5" / "Model 5 Experiment 1", HERE):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import build_e2 as B      # noqa: E402  arm designs, contract, id map
import ruler as R         # noqa: E402  registered nested protocol
import transfer_eval as tv  # noqa: E402  frozen fit_predict

# The alphas to probe, fixed now. The incumbent (3.0) is already scored externally and
# is NOT regenerated - that would waste a slot on a deterministic metric.
PROBE_ALPHAS: Tuple[float, ...] = (0.3, 30.0)
INCUMBENT_ALPHA = 3.0
INCUMBENT_SCORE = 55.80591


def internal_curve(X: np.ndarray, Y: np.ndarray, fams: List[str]) -> Dict[float, float]:
    """Family-out error at every grid alpha, on all 24 soils. This is the ruler's shape."""
    return R.alpha_curve(X, Y, fams)


def main() -> int:
    print("=" * 76)
    print("MODEL 8 / EXPERIMENT 2 - EXTERNAL ALPHA CURVE (two probes, pre-registered)")
    print("=" * 76)

    f, sub_id = B.load_features()
    sample_sub = pd.read_csv(ROOT / "data" / "sample_submission.csv")
    sample_ids = sample_sub.sample_id.astype(str).tolist()

    _, Y, fams, ids = R.design()
    f = f.set_index("sample_id")
    test_ids = [s for s in f.index.astype(str) if f.loc[s, "split"] == "test"]
    id_map = {s: sub_id[s] for s in test_ids}

    designs = B.arm_designs(f, ids, test_ids)
    Xtr, Xte, cols = designs["E2-A"]
    print("[ok] E2-A design: %d train x %d features, %d test" % (Xtr.shape[0], len(cols), Xte.shape[0]))

    # ---- GATE: reproduce the incumbent before generating anything -------------
    # alpha=3 must regenerate E2-A bit-exactly. If it does not, the probe files would
    # be generated by a pipeline that does not match the one that scored 55.8, and every
    # point on the curve would belong to a different model.
    prior = pd.read_csv(HERE / "Submission_Model8_E2_E2A.csv")
    P3, _ = B.fit_full(Xtr, Y, fams, Xte)
    by_sub = {id_map[t]: P3[k] for k, t in enumerate(test_ids)}
    rebuilt = np.array([[by_sub[i][j] for i in sample_ids]
                        for j in range(len(B.SUPPORTS))]).T
    gap = float(np.max(np.abs(rebuilt - prior[list(B.SUPPORTS)].to_numpy(float))))
    ok = gap <= 1e-6
    print("\n--- GATE G5: does alpha=3.0 regenerate the 55.80591 submission? ---")
    print("[%s] max abs difference vs Submission_Model8_E2_E2A.csv = %.3e"
          % ("ok" if ok else "FAIL", gap))
    if not ok:
        print("GATE G5 FAILED - the probe files would not be on the same model as the")
        print("incumbent score, so the curve would be meaningless. Nothing written.")
        return 1

    # ---- the internal curve, for shape comparison ---------------------------
    print("\n--- internal family-out error across the alpha grid (ruler's shape) ---")
    curve = internal_curve(Xtr, Y, fams)
    best = min(curve, key=curve.get)
    for al in sorted(curve):
        mark = "  <- internal argmin" if al == best else ""
        print("    alpha %-10g %8.4f%s" % (al, curve[al], mark))
    spread = max(curve.values()) - min(curve.values())
    print("    internal spread across the WHOLE grid: %.3f EMD" % spread)
    print("    NOTE: the internal spread is what a selection rule is choosing between.")
    print("          If it is small, the ruler cannot resolve alpha at all.")

    # ---- generate the two probes --------------------------------------------
    print("\n--- generating probes (BOTH will be submitted; no selection between them) ---")
    rows = []
    for al in PROBE_ALPHAS:
        P = tv.fit_predict(Xtr, Y, Xte, al)
        by_sub = {id_map[t]: P[k] for k, t in enumerate(test_ids)}
        data = {"sample_id": sample_ids}
        for j, s in enumerate(B.SUPPORTS):
            data[s] = [by_sub[i][j] for i in sample_ids]
        df = pd.DataFrame(data)[list(B.SUPPORTS)].round(6)
        df.insert(0, "sample_id", sample_ids)
        B.assert_contract(df, sample_ids, "alpha=%g" % al)
        out = HERE / ("Submission_Model8_E2_alpha%s.csv" % str(al).replace(".", "p"))
        df.to_csv(out, index=False)
        print("    alpha %-8g -> %-42s [contract ok]" % (al, out.name))
        rows.append({"alpha": al, "internal_familyout": curve[float(al)],
                     "submission": out.name, "external": None})

    pd.DataFrame(rows).to_csv(HERE / "alpha_probe.csv", index=False)
    (HERE / "alpha_probe_manifest.json").write_text(json.dumps({
        "incumbent": {"alpha": INCUMBENT_ALPHA, "external": INCUMBENT_SCORE,
                      "internal_nested": B.G0_VALUE,
                      "submission": "Submission_Model8_E2_E2A.csv"},
        "probes": [{"alpha": al, "external": None} for al in PROBE_ALPHAS],
        "internal_argmin": best,
        "internal_spread_full_grid": spread,
        "gate_g5_reproduction_gap": gap,
        "rule": "BOTH probes are submitted. The curve is the result; the argmin is "
                "incidental and is NOT claimed as an improvement.",
    }, indent=2), encoding="ascii")

    print("\n" + "=" * 76)
    print("Two probe CSVs written and contract-asserted. Awaiting Kaggle results.")
    print("Submit BOTH. Do not pick between them - the shape of the curve is the finding.")
    print("=" * 76)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())